name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
    - name: Checkout
      uses: actions/checkout@master
    - name: Install
      run: yarn
    - name: Build
      run: yarn build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Stetup Node
      uses: actions/setup-node@v1
    - name: Checkout
      uses: actions/checkout@master
    - name: Install
      run: yarn
    - name: Test
      run: yarn test
    - name: Coverage
      if: github.ref == 'refs/heads/master'
      uses: docker://peaceiris/gh-pages:v2.5.0
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: coverage
        PUBLISH_DIR: ./coverage

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
    - name: Checkout
      uses: actions/checkout@master
    - name: Install
      run: yarn
    - name: Build
      run: yarn build
    - name: Release
      run: yarn release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
